version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - vite
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/app/node_modules
    ports:
      - '3000:3000'

    environment:
      - HISTFILE=/usr/src/app/log/.bash_history

  vite:
    build: .
    command: bash -c "vite dev"
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - '3036:3036'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/app/node_modules
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=comaped_dev
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
